FROM public.ecr.aws/lambda/python:3.12

COPY processing/requirements.txt ./requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY IAlirtCode/ialirt_pointing_schedule.py .
COPY IAlirtCode/ialirt_coverage.py .

CMD ["ialirt_pointing_schedule.lambda_handler"]
