"""add_dep_hash_and_image_digest_columns.

Revision ID: 8b55a2a0a9ea
Revises:
Create Date: 2026-04-29 15:51:29.592052

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8b55a2a0a9ea"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "processing_job_table",
        sa.Column("container_image_digest", sa.String(), nullable=True),
    )
    op.add_column(
        "processing_job_table", sa.Column("dependency_hash", sa.String(), nullable=True)
    )
    op.drop_index(
        op.f("idx_unique_status"),
        table_name="processing_job_table",
        postgresql_where="(status = ANY"
        " (ARRAY['INPROGRESS'::status, 'SUCCEEDED'::status]))",
    )
    op.create_index(
        "idx_unique_status",
        "processing_job_table",
        [
            "instrument",
            "data_level",
            "descriptor",
            "start_date",
            "container_image_digest",
            "dependency_hash",
            sa.literal_column("coalesce(repointing, -1)"),
        ],
        unique=True,
        postgresql_where=sa.text("status IN ('INPROGRESS', 'SUCCEEDED')"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_unique_status",
        table_name="processing_job_table",
        postgresql_where=sa.text("status IN ('INPROGRESS', 'SUCCEEDED')"),
    )
    op.create_index(
        op.f("idx_unique_status"),
        "processing_job_table",
        [
            "instrument",
            "data_level",
            "descriptor",
            "start_date",
            "version",
            "repointing",
        ],
        unique=True,
        postgresql_where="(status = "
        "ANY (ARRAY['INPROGRESS'::status, 'SUCCEEDED'::status]))",
    )
    op.drop_column("processing_job_table", "dependency_hash")
    op.drop_column("processing_job_table", "container_image_digest")
    # ### end Alembic commands ###
