"""create_idex_l0_table.

Revision ID: e9295ca9d77e
Revises: 8b55a2a0a9ea
Create Date: 2026-05-07 11:35:33.650544

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e9295ca9d77e"
down_revision: str | Sequence[str] | None = "8b55a2a0a9ea"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "idex_l0_files",
        sa.Column("file_path", sa.String(), nullable=False),
        sa.Column("start_date", sa.DateTime(), nullable=False),
        sa.Column("version", sa.String(length=2), nullable=False),
        sa.Column("ingestion_date", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("file_path", "start_date"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("idex_l0_files")
    # ### end Alembic commands ###
