"""create_release_file_table.

Revision ID: f52014ca1da4
Revises: e9295ca9d77e
Create Date: 2026-05-08 07:54:44.988585

"""

from collections.abc import Sequence

import imap_data_access
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f52014ca1da4"
down_revision: str | Sequence[str] | None = "e9295ca9d77e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "release_files",
        sa.Column("file_path", sa.String(), nullable=False),
        sa.Column(
            "instrument",
            postgresql.ENUM(
                *imap_data_access.VALID_INSTRUMENTS,
                name="instrument",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("descriptor", sa.String(), nullable=False),
        sa.Column("start_date", sa.DateTime(), nullable=False),
        sa.Column("end_date", sa.DateTime(), nullable=True),
        sa.Column("version", sa.String(length=4), nullable=False),
        sa.Column("extension", sa.String(), nullable=False),
        sa.Column("ingestion_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("released", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("file_path"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("release_files")
    # ### end Alembic commands ###
